const V = require('../core/shifts.js'); const assert = require('assert');
assert.strictEqual(V.parseTime('9am'), '09:00'); assert.strictEqual(V.parseTime('2:30 pm'), '14:30'); assert.strictEqual(V.parseTime('12am'), '00:00'); assert.strictEqual(V.parseTime('25'), ''); assert.strictEqual(V.parseTime('930'), '09:30');
assert.strictEqual(V.cleanContact('(555) 123 4567').value, '555-123-4567'); assert.strictEqual(V.cleanContact('1-555-123-4567').value, '555-123-4567');
assert.strictEqual(V.cleanContact(' A@B.com ').value, 'a@b.com'); assert.ok(!V.cleanContact('hello').ok); assert.ok(!V.cleanContact('').ok);
const r = V.makeShifts({ title: 'T', date: '2026-10-31', start: '9am', end: '11am', needed: 2, repeat: 'weekly', count: 3 });
assert.ok(r.ok); assert.deepStrictEqual(r.shifts.map(s => s.date), ['2026-10-31', '2026-11-07', '2026-11-14']);
assert.ok(!V.makeShifts({ title: '', date: '', start: '', needed: 0 }).ok);
const d = V.emptyData(); d.shifts.push(r.shifts[0]);
assert.ok(V.addSignup(d, r.shifts[0].id, 'Ann', '555-111-2222').ok);
assert.ok(!V.addSignup(d, r.shifts[0].id, 'Ann', '555-999-2222').ok, 'dupe name');
assert.ok(V.addSignup(d, r.shifts[0].id, 'Bo', 'bo@x.org').ok);
assert.strictEqual(V.shiftStatus(d, r.shifts[0]).state, 'full');
assert.ok(!V.addSignup(d, r.shifts[0].id, 'Cy', 'cy@x.org').ok, 'full');
assert.ok(V.toCSV(d).includes('Ann')); assert.ok(V.toCSV({shifts:[],signups:[]}).startsWith('Date'));
assert.ok(V.cleanName('=x') === '=x' && V.toCSV((() => { const e = V.emptyData(); const s = V.makeShifts({title:'=cmd',date:'2026-01-01',start:'9',needed:1}).shifts[0]; e.shifts.push(s); return e; })()).includes("'=cmd"));
const rm = V.removeShift(d, r.shifts[0].id); assert.strictEqual(d.signups.length, 0); V.restoreShift(d, rm); assert.strictEqual(d.signups.length, 2);
const old = V.clearOlderThan(d, '2027-01-01'); assert.strictEqual(d.shifts.length, 0); assert.strictEqual(old.signups.length, 2);
global.window = {}; require('../examples/sample.js'); const sd = V.sampleData(global.window.VOLUNTEER_SAMPLE);
assert.ok(sd.shifts.length >= 8); assert.ok(V.sanitize(JSON.parse(JSON.stringify(sd))).signups.length === sd.signups.length);
assert.ok(V.reminderMessage(sd, sd.shifts[0], 'Org').includes('Hi Maria'));
assert.ok(V.gapMessage(sd, V.todayISO(), 'Org').includes('need'));
console.log('all core tests passed');
