const assert = require('assert'); const P = require('../core/pantry.js');
const d = P.empty();
const it = P.addItem(d, { name: 'Canned corn', category: 'Canned vegetables', unit: 'each', lbPer: 0.9, low: 10 }).item;
const rice = P.addItem(d, { name: 'Rice', unit: 'lb', low: 20 }).item;
assert(P.addItem(d, { name: ' canned CORN ' }).error, 'duplicate blocked');
assert(P.addMove(d, { type: 'in', itemId: it.id, qty: 0 }).error, 'zero qty blocked');
assert(P.addMove(d, { type: 'in', itemId: it.id, qty: 30, date: '13/45/2026' }).error, 'bad date');
P.addMove(d, { type: 'in', itemId: it.id, qty: 30, donor: 'Valley Grocery' });
P.addMove(d, { type: 'in', itemId: rice.id, qty: '15,5' });
assert.strictEqual(P.stockOf(d, it.id), 30);
let r = P.addMove(d, { type: 'out', itemId: it.id, qty: 22, household: ' h-014 ', size: '4' });
assert.strictEqual(r.move.household, 'H-014');
let list = P.stockList(d);
assert(list.every(x => x.status === 'low'));
assert.strictEqual(P.totals(d).lbs, P.round(8 * 0.9 + 15.5));
assert(P.addMove(d, { type: 'out', itemId: it.id, qty: 50 }).warning, 'oversell warns');
assert.strictEqual(P.stockList(d).find(x => x.item.id === it.id).stock, 0);
const before = P.stockOf(d, it.id); const rm = P.removeMove(d, r.move.id); assert.strictEqual(P.stockOf(d, it.id), before + 22);
P.restoreMove(d, rm);
assert.strictEqual(P.cleanHousehold('j.s.'), 'JS');
assert.strictEqual(P.parseDate('10/9/26'), '2026-10-09');
assert.strictEqual(P.lastSize(d, 'h-014'), 4);
assert(P.stockCsv(d).includes('Canned corn'));
assert(P.sanitize({ items: [{ name: '=BAD' }], moves: [{ itemId: 'nope', type: 'in', qty: 1 }] }).moves.length === 0);
assert(P.activityCsv(P.sanitize(JSON.parse(JSON.stringify(d)))).split('\r\n').length === d.moves.length + 1);
const bef = P.stockOf(d, rice.id);
assert(P.adjustStock(d, rice.id, 'abc').error && P.adjustStock(d, rice.id, '').error && P.adjustStock(d, rice.id, -2).error);
assert(P.adjustStock(d, rice.id, bef).unchanged);
P.adjustStock(d, rice.id, 12); assert.strictEqual(P.stockOf(d, rice.id), 12);
assert.strictEqual(P.sanitize(JSON.parse(JSON.stringify(d))).moves.filter(m => m.type === 'adj').length, 1);
assert(P.activityCsv(d).includes('Count correction'));
assert(P.updateItem(d, rice.id, { name: 'canned corn' }).error, 'dup rename blocked');
P.updateItem(d, rice.id, { name: 'White rice', low: '5' }); assert.strictEqual(P.findItem(d, rice.id).low, 5);
console.log('core tests passed');
