// Needs jsdom: NODE_PATH=/path/to/node_modules node tests/ui-smoke.js <built index.html>
const { JSDOM } = require('jsdom'); const fs = require('fs'); const assert = require('assert');
const dom = new JSDOM(fs.readFileSync(process.argv[2], 'utf8'), { runScripts: 'dangerously', url: 'http://localhost/' });
const w = dom.window, $ = s => w.document.querySelector(s);
const click = s => { const e = typeof s === 'string' ? $(s) : s; assert(e, 'missing ' + s); e.dispatchEvent(new w.MouseEvent('click', { bubbles: true })); };
const set = (s, v) => { const e = $(s); assert(e, 'missing ' + s); e.value = v; e.dispatchEvent(new w.Event('change', { bubbles: true })); };
w.scrollTo = () => {};
assert($('h1').textContent.includes('Maple Hollow'));
assert($('.stats'), 'home stats'); click('[data-act=welcomed]');
click('[data-log=out]'); assert($('#f-household'));
click('[data-act=saveLog]'); assert($('.err'), 'needs household');
set('#f-household', 'zz1'); set('#f-size', '3');
const opt = [...w.document.querySelectorAll('#f-item option')].find(o => o.value); set('#f-item', opt.value); set('#f-qty', '2');
click('[data-act=saveMore]'); assert($('.alert.ok'), 'saved another'); assert($('#f-household').value === 'ZZ1' || $('#f-household').value === 'zz1');
set('#f-item', opt.value); set('#f-qty', '1'); click('[data-act=saveLog]');
assert($('.toast'), 'toast'); assert(w.document.body.textContent.includes('Saved:'));
click('[data-act=undo]'); assert(!$('.toast'));
click('[data-log=in]'); click('[data-act=toggleNew]'); set('#n-name', 'Test jam'); set('#n-low', '3'); set('#f-qty', '5'); click('[data-act=saveLog]');
click('[data-go=stock]'); assert(w.document.body.textContent.includes('Test jam'));
const names = () => [...w.document.querySelectorAll('tbody tr td:first-child')].map(e => e.firstChild.textContent);
click('[data-sort=item]'); const a = names(); assert.deepStrictEqual(a, [...a].sort((x, y) => x.toLowerCase() < y.toLowerCase() ? -1 : 1));
click('[data-sort=item]'); assert.deepStrictEqual(names(), a.slice().reverse());
const stocks = () => [...w.document.querySelectorAll('tbody tr td.n:nth-child(2)')].map(e => parseFloat(e.textContent));
click('[data-sort=stock]'); const s1 = stocks(); assert.deepStrictEqual(s1, [...s1].sort((x, y) => x - y));
click('[data-sort=low]'); click('[data-sort=status]'); assert($('th[aria-sort=ascending]'));
click('[data-edit]'); assert($('#e-count')); set('#e-low', '77'); set('#e-count', '5'); click('[data-act=saveEdit]');
assert($('.toast') && w.document.body.textContent.includes('77'), 'edit saved'); 
click('[data-go=activity]'); assert($('[data-del]')); click('[data-del]'); assert($('.toast'));
click('[data-go=more]'); assert($('[data-act=backup]'));
let saved = null; w.ToolkitDownload.save = (n, t) => { saved = { n, t }; };
click('[data-act=backup]'); assert(saved.n.startsWith('pantry-backup') && JSON.parse(saved.t).data.items.length, 'backup saved');
click('[data-act=stockCsv]'); assert(saved.n.endsWith('.csv') && saved.t.startsWith('\ufeffItem,'), 'stock csv');
click('[data-act=theme]'); assert(w.document.documentElement.classList.contains('light'));
console.log('ui smoke passed');
